/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/Collections/PtrHashSet.cs(23,26): error CS0307: The namespace 'PtrHash' cannot be used with type arguments [/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/PtrHash.CSharp.Port.csproj]
/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/Collections/PtrHashHashSet.cs(22,26): error CS0307: The namespace 'PtrHash' cannot be used with type arguments [/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/PtrHash.CSharp.Port.csproj]
/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/Collections/PtrHashDictionary.cs(22,26): error CS0307: The namespace 'PtrHash' cannot be used with type arguments [/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/PtrHash.CSharp.Port.csproj]
/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/Storage/CachelineEfVec.cs(14,91): error CS0246: The type or namespace name 'IStaticRemappingStorage<>' could not be found (are you missing a using directive or an assembly reference?) [/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/PtrHash.CSharp.Port.csproj]
/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/Storage/CachelineEfVec.cs(190,42): error CS0246: The type or namespace name 'IMutableRemappingStorage' could not be found (are you missing a using directive or an assembly reference?) [/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/PtrHash.CSharp.Port.csproj]
/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/Storage/CachelineEfVec.cs(195,23): error CS0246: The type or namespace name 'IMutableRemappingStorage' could not be found (are you missing a using directive or an assembly reference?) [/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/PtrHash.CSharp.Port.csproj]
/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/Storage/CachelineEfVec.cs(195,23): error CS0538: 'IMutableRemappingStorage' in explicit interface declaration is not an interface [/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/PtrHash.CSharp.Port.csproj]
/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/Storage/CachelineEfVec.cs(190,16): error CS0246: The type or namespace name 'IMutableRemappingStorage' could not be found (are you missing a using directive or an assembly reference?) [/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/PtrHash.CSharp.Port.csproj]
/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/Storage/CachelineEfVec.cs(190,42): error CS0538: 'IMutableRemappingStorage' in explicit interface declaration is not an interface [/home/jared/Developer/PtrHash/PtrHash.CSharp.Port/PtrHash.CSharp.Port.csproj]

The build failed. Fix the build errors and run again.
